version: "3.3"

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "@pass"
      POSTGRES_DB: dbname   
      PGDATA: /var/lib/postgresql/data/pgdata     
    volumes:
      - "./db:/var/lib/postgresql/data"

